name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

# Cancel in-progress workflows on new pushes to same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_VERSION: "0.4.18"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Don't cancel other matrix jobs on failure
      matrix:
        python-version: ["3.11", "3.12"]
        include:
          - python-version: "3.12"
            coverage: true # Only run coverage on one version

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      # Optimized system dependencies with caching
      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gdal-bin libgdal-dev gcc g++ pkg-config libspatialindex-dev
          version: 1.0

      - name: Set GDAL environment variables
        run: |
          export GDAL_VERSION=$(gdal-config --version)
          echo "GDAL_VERSION=$GDAL_VERSION" >> $GITHUB_ENV
          echo "CPLUS_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV
          echo "C_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV

          # Verify GDAL installation
          gdal-config --version

      # Cache UV dependencies for faster builds
      - name: Cache UV dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ matrix.python-version }}-
            uv-${{ runner.os }}-

      - name: Install dependencies
        run: uv sync --all-extras --frozen

      - name: Verify installation
        run: |
          uv run python -c "import geopandas; print('GeoPandas version:', geopandas.__version__)"
          uv run python -c "import fastapi; print('FastAPI version:', fastapi.__version__)"

      - name: Run linting
        run: |
          uv run ruff check . --output-format=github
          uv run ruff format --check .

      - name: Run type checking
        run: uv run mypy app/ --install-types --non-interactive

      - name: Run unit tests
        run: |
          if [ "${{ matrix.coverage }}" = "true" ]; then
            uv run pytest tests/ -v --cov=app --cov-report=xml --cov-report=term-missing
          else
            uv run pytest tests/ -v
          fi
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY || 'mock-key-for-testing' }}

      - name: Run integration tests (non-blocking)
        continue-on-error: true # Integration tests may fail due to external services
        run: uv run pytest tests/test_connectors/ tests/test_services/ -v --maxfail=3
        env:
          INTEGRATION_TESTS: true
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY || 'mock-key-for-testing' }}

      - name: Upload coverage reports
        if: matrix.coverage == true
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        run: uv python install 3.11

      - name: Cache UV dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-security-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run security audit
        run: |
          uv run pip-audit --desc --format=json --output=security-report.json
          uv run pip-audit --desc  # Human readable output

      - name: Upload security report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-report.json

  # PR-specific validation job
  pr-validation:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better analysis

      - name: Validate PR title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "Validating PR title: $PR_TITLE"

          # Check conventional commit format
          if [[ ! "$PR_TITLE" =~ ^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+ ]]; then
            echo "❌ PR title must follow conventional commit format"
            echo "Examples: feat: add new feature, fix(api): resolve bug"
            exit 1
          fi
          echo "✅ PR title format is valid"

      - name: Check for PRP completion
        run: |
          # Check if PR description mentions PRP step completion
          PR_BODY="${{ github.event.pull_request.body }}"
          if [[ "$PR_BODY" == *"PRP Step"* ]]; then
            echo "✅ PR appears to be PRP-related"
          else
            echo "⚠️  PR doesn't mention PRP step - ensure proper documentation"
          fi

      - name: Analyze changed files
        run: |
          echo "📁 Changed files in this PR:"
          git diff --name-only origin/${{ github.base_ref }}..HEAD

          # Check for sensitive files
          if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -E "(\.env|secrets|password)"; then
            echo "⚠️  Warning: Potentially sensitive files changed"
          fi

  build:
    needs: [test, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-tags: ${{ steps.meta.outputs.tags }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64 # Multi-platform support
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Add build args for optimization
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production

    steps:
      - name: Deploy to production
        run: |
          echo "🚀 Deploying to production..."
          echo "📦 Image: ${{ needs.build.outputs.image-tags }}"
          echo "🔍 Digest: ${{ needs.build.outputs.image-digest }}"

          # Placeholder for actual deployment
          echo "🔄 Would deploy using:"
          echo "   - Docker Compose"
          echo "   - Kubernetes"
          echo "   - Cloud Run"
          echo "   - or other deployment method"

      - name: Create deployment status
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: context.payload.deployment?.id || 'manual',
              state: 'success',
              description: 'Deployment completed successfully',
              environment_url: 'https://your-production-url.com'
            })
